GET http://localhost:3000/health
###
GET http://localhost:3000/
###
POST http://localhost:3000/v1/auth/register
Content-Type: application/json

{
  "userName": "Leah",
  "email": "leahb307@gmail.com",
  "password": "Password123"
}

###
POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
  "email": "leahb307@gmail.com",
  "password": "Password123"
}

###
POST http://localhost:3000/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTE1NjNlMTI1ZTgwNTJiZGFiOWYzZTYiLCJpYXQiOjE3Nzk3OTU3MDl9.L3slKh0UY8jVZqoD8cxlC-Stcnu_iIyOlR8uPR1p-EA
